# Generated by Django 4.2 on 2025-03-03 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_description',
            field=models.TextField(blank=True, help_text='Description of the company'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(help_text='Name of the company', max_length=200),
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo of the company', upload_to='employer_logos/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(help_text='One-to-one relationship with the User model', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employer_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.URLField(blank=True, help_text='Website URL of the company'),
        ),
    ]
