# Generated by Django manually

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_industry"),
    ]

    operations = [
        # This is a placeholder migration to replace the problematic one
        # No actual operations needed - table already exists
    ]

