# Generated by Django 4.2 on 2025-03-03 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_alter_employer_company_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_merge_0003_job_applications_0003_savedsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applications',
            field=models.IntegerField(default=0, help_text='Number of applications for the job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the job was created'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(help_text='Description of the job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(help_text='Foreign key to the Employer model', on_delete=django.db.models.deletion.CASCADE, to='employers.employer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the job (optional)', upload_to='job_images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry of the job (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(help_text='Location of the job', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(help_text='Salary for the job', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(help_text='Title of the job', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='views',
            field=models.IntegerField(default=0, help_text='Number of views for the job'),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the search was saved'),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry for the search (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='query',
            field=models.CharField(blank=True, help_text='Search query (optional)', max_length=200),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='user',
            field=models.ForeignKey(help_text='Foreign key to the User model', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
