openapi: 3.0.0
info:
  title: V1PromoJobs API
  version: 1.0.0
paths:
  /accounts/api-token-auth/:
    post:
      summary: Obtain authentication token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid request
        '401':
          description: Invalid credentials
