# Generated by Django 4.2 on 2025-03-03 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('job_search', 'Job Search'), ('job_view', 'Job View'), ('application_submitted', 'Application Submitted'), ('employer_profile_view', 'Employer Profile View')], help_text='Type of user activity (e.g., login, job_search)', max_length=255),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='details',
            field=models.JSONField(blank=True, help_text='Additional details about the activity', null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time of the activity'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(help_text='Foreign key to the User model', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
