# Generated by Django 4.2 on 2025-02-23 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_applications'),
        ('jobs', '0003_savedsearch'),
    ]

    operations = [
    ]
