# Generated by Django manually

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        # This is a placeholder migration to replace the problematic one
        # No actual operations needed
    ]

