# Generated by Django 4.2 on 2025-02-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, upload_to='employer_logos/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
